import type { DataCollection } from '../types';

export const ARCHITECTURE_DATA: DataCollection[] = [
  {
    collectionTitle: "Keyword General Architecture",
    categories: [
      { 
        title: "Architectural Vocabulary", 
        keywords: [
            { term: "Adjustment", explanation: "Penyesuaian atau modifikasi kecil pada desain untuk mencapai keselarasan atau fungsi yang lebih baik." },
            { term: "Architectonic", explanation: "Berkaitan dengan arsitektur atau konstruksi yang memiliki kualitas arsitektural yang kuat dan terstruktur." },
            { term: "Articulation", explanation: "Cara elemen-elemen arsitektur disambungkan atau dibedakan secara visual untuk memperjelas bentuk dan fungsi." },
            { term: "Biomimicry", explanation: "Inovasi desain yang meniru model, sistem, dan elemen alam untuk memecahkan masalah manusia." },
            { term: "Biomorphic", explanation: "Bentuk desain yang terinspirasi dari bentuk-bentuk organik atau alami, seperti tanaman atau hewan." },
            { term: "Building Envelope", explanation: "Selubung luar bangunan yang memisahkan bagian dalam dari lingkungan luar, termasuk dinding, atap, dan jendela." },
            { term: "Cladding", explanation: "Lapisan material eksterior yang dipasang pada dinding bangunan untuk proteksi dan estetika." },
            { term: "Cloister", explanation: "Koridor beratap yang biasanya mengelilingi halaman dalam sebuah biara atau bangunan keagamaan." },
            { term: "Colossal", explanation: "Struktur atau elemen yang ukurannya sangat besar dan megah, melebihi skala manusia." },
            { term: "Composite", explanation: "Material yang terbuat dari dua atau lebih bahan berbeda yang digabungkan untuk kekuatan atau kualitas tertentu." },
            { term: "Craft", explanation: "Keterampilan dan keahlian tangan dalam menciptakan atau membangun sesuatu dengan detail dan kualitas tinggi." },
            { term: "Decal", explanation: "Gambar atau desain dekoratif yang dapat ditransfer ke permukaan lain, sering digunakan untuk hiasan dinding." },
            { term: "Diagram", explanation: "Representasi grafis sederhana dari sebuah konsep, proses, atau struktur dalam arsitektur." },
            { term: "Jaali", explanation: "Layar atau jendela berlubang dengan pola geometris atau floral, umum dalam arsitektur Indo-Islam." },
            { term: "Liminal", explanation: "Ruang transisi atau ambang batas antara dua area yang berbeda, seperti lorong atau pintu masuk." },
            { term: "Finstype", explanation: "Jenis jendela atau bukaan yang menonjol keluar dari dinding, seringkali untuk ventilasi atau cahaya." },
            { term: "Kuratyny", explanation: "Istilah yang kemungkinan merujuk pada tirai atau penutup jendela dalam konteks arsitektur." },
            { term: "Menchev", explanation: "Istilah yang kurang umum, mungkin merujuk pada elemen atau gaya arsitektur regional tertentu." },
            { term: "Penetration", explanation: "Bukaan atau lubang yang menembus permukaan solid seperti dinding atau atap." },
            { term: "Penteconter", explanation: "Kapal perang Yunani kuno dengan 50 pendayung, yang arsitekturnya mempengaruhi struktur bangunan." },
            { term: "Semidetached", explanation: "Rumah yang satu dindingnya menyatu dengan rumah lain, membentuk satu bangunan berisi dua unit." },
            { term: "Straddling", explanation: "Posisi sebuah struktur yang dibangun di atas atau melintasi dua titik atau area terpisah." },
            { term: "Suhail", explanation: "Istilah yang mungkin merujuk pada elemen arsitektur tradisional di Timur Tengah atau Asia Selatan." },
            { term: "Sullage", explanation: "Air limbah dari aktivitas domestik seperti mandi dan mencuci, yang perlu dikelola dalam desain bangunan." },
            { term: "Foliation", explanation: "Ornamen dekoratif yang berbentuk daun atau dedaunan." },
            { term: "Turret", explanation: "Menara kecil yang menonjol dari sudut atau atap sebuah bangunan, seringkali pada kastil." },
            { term: "Form", explanation: "Bentuk tiga dimensi dari sebuah objek atau bangunan, yang merupakan elemen dasar desain." },
            { term: "Gallilee", explanation: "Serambi atau kapel di pintu masuk sebuah gereja, berfungsi sebagai area transisi." },
            { term: "Calles", explanation: "Istilah Spanyol untuk 'jalan', dalam konteks urbanisme merujuk pada desain dan tata letak jalan." },
            { term: "Hierarchy", explanation: "Susunan elemen dalam desain berdasarkan tingkat kepentingannya, menciptakan fokus visual." },
            { term: "High-Pitched", explanation: "Atap dengan kemiringan yang sangat curam." },
            { term: "High-Tech", explanation: "Gaya arsitektur yang menonjolkan elemen teknologi, industri, dan struktur bangunan secara eksplisit." },
            { term: "Homogeneous", explanation: "Terdiri dari elemen-elemen yang seragam atau serupa dalam tampilan dan material." },
            { term: "Hypostyle", explanation: "Ruangan besar dengan atap yang ditopang oleh banyak kolom atau pilar." },
            { term: "Imbricate", explanation: "Susunan elemen yang saling tumpang tindih seperti sisik ikan atau genteng." },
            { term: "Joggle Post", explanation: "Tiang vertikal yang memiliki tonjolan untuk menopang balok lain." },
            { term: "Juncture", explanation: "Titik pertemuan atau sambungan antara dua atau lebih elemen bangunan." },
            { term: "Juxtaposition", explanation: "Penempatan dua elemen yang kontras secara berdampingan untuk menciptakan efek visual." },
            { term: "Kinect", explanation: "Teknologi sensor gerak yang dapat digunakan dalam desain interaktif dan arsitektur responsif." },
            { term: "Lancet", explanation: "Jendela tinggi dan ramping dengan ujung atas melengkung runcing, khas arsitektur Gotik." },
            { term: "Lintel", explanation: "Balok horizontal di atas bukaan seperti pintu atau jendela yang menopang beban di atasnya." },
            { term: "Lisail", explanation: "Bagian layar tambahan pada kapal layar, yang prinsip aerodinamisnya dapat diterapkan dalam arsitektur." },
            { term: "Measuring", explanation: "Proses pengukuran yang presisi sebagai dasar perencanaan dan konstruksi arsitektur." },
            { term: "Merge", explanation: "Penggabungan dua atau lebih bentuk atau ruang menjadi satu kesatuan yang harmonis." },
            { term: "Module", explanation: "Unit standar yang dapat diulang dan digabungkan untuk membentuk struktur yang lebih besar." },
            { term: "Naos", explanation: "Ruang utama bagian dalam sebuah kuil Yunani kuno, tempat patung dewa berada." },
            { term: "Order", explanation: "Sistem aturan desain dalam arsitektur klasik (Doric, Ionic, Corinthian) yang menentukan bentuk dan proporsi kolom serta elemen lainnya." },
            { term: "Orientation", explanation: "Arah hadap bangunan terhadap matahari, angin, dan lingkungan sekitar untuk optimalisasi cahaya dan energi." },
            { term: "Palafitte", explanation: "Rumah panggung yang dibangun di atas air, seperti di danau atau rawa." },
            { term: "Plinth", explanation: "Bagian dasar atau alas dari sebuah kolom, patung, atau dinding." },
            { term: "Polychrome", explanation: "Penggunaan banyak warna dalam dekorasi arsitektur, baik di eksterior maupun interior." },
            { term: "Joty", explanation: "Istilah yang tidak umum dalam arsitektur standar, mungkin merujuk pada elemen dekoratif atau vernakular." },
            { term: "Bust", explanation: "Patung setengah badan seseorang, sering digunakan sebagai elemen dekoratif dalam interior klasik." },
            { term: "Postiche", explanation: "Ornamen tambahan atau elemen palsu yang ditambahkan pada bangunan untuk tujuan dekoratif." }
        ]
      },
      { 
        title: "Quality", 
        keywords: [
            { term: "Lifestyle", explanation: "Desain yang mendukung atau mencerminkan gaya hidup penghuninya." },
            { term: "Queen Post", explanation: "Dua tiang vertikal dalam struktur rangka atap kayu yang menopang balok utama." },
            { term: "Rampart", explanation: "Benteng pertahanan berupa gundukan tanah atau dinding tebal yang mengelilingi suatu area." },
            { term: "Rusticate", explanation: "Teknik finishing pada batu atau beton yang memberikan tampilan kasar dan menonjolkan sambungan." },
            { term: "Scale", explanation: "Perbandingan ukuran antara satu elemen dengan elemen lain, atau dengan skala manusia." },
            { term: "Sheer", explanation: "Material yang tipis dan transparan, seperti tirai, yang memungkinkan cahaya masuk." },
            { term: "Shaft", explanation: "Bagian utama yang vertikal dari sebuah kolom, di antara dasar dan kepala kolom." },
            { term: "Sofa", explanation: "Perabot duduk panjang berlapis kain dengan sandaran punggung dan lengan." },
            { term: "Sofita", explanation: "Permukaan bawah dari elemen arsitektur yang menjorok, seperti atap teritisan atau balkon." },
            { term: "Softlight", explanation: "Pencahayaan yang menyebar dan tidak menghasilkan bayangan tajam, menciptakan suasana lembut." },
            { term: "Stalactite", explanation: "Ornamen gantung yang menyerupai stalaktit di gua, sering ditemukan pada arsitektur Islam (Muqarnas)." },
            { term: "Mortality", explanation: "Konsep kefanaan atau kematian yang dapat direfleksikan dalam desain arsitektur monumental atau memorial." },
            { term: "Nothing", explanation: "Penggunaan kekosongan atau ruang negatif sebagai elemen desain yang penting dan bermakna." },
            { term: "Pili", explanation: "Tiang atau pilar besar yang berfungsi sebagai penyangga utama struktur." },
            { term: "Storey", explanation: "Tingkat atau lantai dari sebuah bangunan." },
            { term: "Stria", explanation: "Alur atau goresan vertikal yang dangkal pada permukaan kolom atau dinding." },
            { term: "Stringer", explanation: "Balok struktural miring yang menopang anak tangga pada sebuah tangga." },
            { term: "Stylobate", explanation: "Dasar bertingkat tempat berdirinya barisan kolom pada kuil Yunani klasik." },
            { term: "Subbase", explanation: "Lapisan pondasi di bawah lantai dasar atau perkerasan." },
            { term: "Substructure", explanation: "Bagian bawah bangunan yang berada di bawah permukaan tanah; pondasi." },
            { term: "Surtaxe", explanation: "Konstruksi tambahan yang dibangun di atas struktur yang sudah ada." },
            { term: "Sustainable", explanation: "Desain yang ramah lingkungan, efisien dalam penggunaan energi dan sumber daya." },
            { term: "Tailpiece", explanation: "Elemen dekoratif atau fungsional di ujung sebuah komponen bangunan." },
            { term: "Texture", explanation: "Kualitas permukaan suatu material yang dapat dirasakan atau dilihat (kasar, halus, dll)." },
            { term: "Uniformity", explanation: "Keseragaman elemen desain dalam hal bentuk, warna, atau ukuran." },
            { term: "Hyper Realistic", explanation: "Gambar atau render yang sangat detail hingga tampak seperti foto asli." },
            { term: "Super High Detail", explanation: "Tingkat kerincian yang sangat tinggi pada semua elemen dalam gambar." },
            { term: "High Quality", explanation: "Kualitas gambar yang superior, tajam, dan bebas dari cacat visual." },
            { term: "High Resolution", explanation: "Gambar dengan jumlah piksel yang sangat banyak, menghasilkan detail yang tajam." },
            { term: "Photorealism", explanation: "Upaya untuk membuat gambar yang tidak bisa dibedakan dari foto." },
            { term: "Super High Resolution", explanation: "Resolusi gambar yang jauh di atas standar, seperti 8K atau lebih." },
            { term: "Very High Resolution", explanation: "Resolusi yang sangat tinggi, memungkinkan pembesaran tanpa kehilangan detail." },
            { term: "Wallpaper", explanation: "Kualitas gambar yang cocok untuk digunakan sebagai latar belakang desktop atau cetak format besar." },
            { term: "Masterpiece", explanation: "Karya dengan kualitas artistik dan teknis tertinggi." },
            { term: "FHD", explanation: "Full High Definition, resolusi standar 1920x1080 piksel." },
            { term: "RAW Photo", explanation: "Gaya visual yang meniru hasil jepretan kamera profesional sebelum diolah." },
            { term: "Huge, Filesize", explanation: "Menunjukkan gambar dengan data yang sangat besar, menyiratkan kualitas dan resolusi tinggi." },
            { term: "2k", explanation: "Resolusi sekitar 2048 piksel lebarnya." },
            { term: "4k", explanation: "Resolusi sekitar 4096 piksel lebarnya, standar untuk visual berkualitas tinggi." },
            { term: "8k", explanation: "Resolusi sangat tinggi, sekitar 8192 piksel lebarnya, untuk detail ekstrem." },
            { term: "16k", explanation: "Resolusi ekstrem yang menghasilkan detail mikroskopis." },
            { term: "Ultra HD", explanation: "Istilah pemasaran untuk resolusi 4K (3840x2160 piksel)." },
            { term: "Ultrarealistic", explanation: "Sangat realistis, melampaui fotorealisme biasa." },
            { term: "Pixel-Perfect", explanation: "Setiap piksel dalam gambar ditempatkan dengan sempurna tanpa cela." },
            { term: "Extreme Definition", explanation: "Tingkat ketajaman dan kejelasan gambar yang luar biasa." },
            { term: "Ultra-Detail", explanation: "Detail yang sangat halus dan rumit terlihat dengan jelas." },
            { term: "Maximum Quality", explanation: "Permintaan untuk kualitas terbaik yang bisa dihasilkan oleh AI." },
            { term: "Visual Masterpiece", explanation: "Sebuah karya visual yang dianggap sebagai pencapaian puncak." },
            { term: "Highest Texture", explanation: "Tekstur material dalam gambar terlihat sangat nyata dan mendetail." },
            { term: "Studio-Quality", explanation: "Kualitas gambar setara dengan hasil foto di studio profesional." },
            { term: "True Colors", explanation: "Warna yang akurat dan sesuai dengan kenyataan." },
            { term: "Stunning Quality", explanation: "Kualitas yang sangat mengesankan dan memukau." },
            { term: "Lifelike Rendering", explanation: "Proses render yang menghasilkan gambar yang tampak hidup." },
            { term: "Supreme Image Quality", explanation: "Kualitas gambar tingkat tertinggi." },
            { term: "Render", explanation: "Proses pembuatan gambar fotorealistik dari model 3D." },
            { term: "Octane Render", explanation: "Mesin render yang dikenal dengan kecepatan dan realisme tinggi." },
            { term: "Corona Render", explanation: "Mesin render yang populer untuk visualisasi arsitektur karena kemudahan dan hasil realistis." },
            { term: "Unreal Engine", explanation: "Mesin render real-time yang sering digunakan untuk visualisasi interaktif dan sinematik." },
            { term: "V-Ray Render", explanation: "Mesin render standar industri untuk arsitektur dan efek visual." },
            { term: "Blender Render", explanation: "Mesin render bawaan atau tambahan pada software Blender (Cycles, Eevee)." },
            { term: "Redshift Render", explanation: "Mesin render yang diakselerasi GPU, dikenal karena kecepatannya." },
            { term: "Arnold Render", explanation: "Mesin render yang digunakan dalam film animasi dan efek visual besar." },
            { term: "Photographer", explanation: "Meniru gaya seorang fotografer tertentu." },
            { term: "Ansel Adams", explanation: "Fotografer lanskap hitam-putih legendaris, dikenal dengan kontras dramatis." },
            { term: "Benny Chan", explanation: "Fotografer arsitektur yang dikenal dengan komposisi dinamis dan penggunaan cahaya." },
            { term: "Iwan Baan", explanation: "Fotografer arsitektur yang menangkap bangunan dalam konteks kehidupan manusia." },
            { term: "Mike Kelley", explanation: "Fotografer yang sering memotret arsitektur, interior, dan industri dengan teknik pencahayaan canggih." },
            { term: "Nick Hufton", explanation: "Bagian dari duo Hufton+Crow, dikenal dengan gambar arsitektur yang bersih dan kuat." },
            { term: "Purnesh Dev Nikhanj", explanation: "Fotografer arsitektur yang dikenal dengan perspektif unik dan penceritaan visual." },
            { term: "Fernando Guerra", explanation: "Fotografer arsitektur Portugis yang karyanya menonjolkan suasana dan narasi." }
        ]
      },
      { title: "Soil Preparation", keywords: [
        { term: "Outdoor", explanation: "Area di luar bangunan, seperti taman, teras, atau halaman." },
        { term: "Indoor", explanation: "Area di dalam bangunan." },
        { term: "Garden Design", explanation: "Seni dan proses merancang dan menciptakan tata letak taman dan lanskap." },
        { term: "Horticulture", explanation: "Ilmu dan seni menanam tanaman, termasuk buah, sayur, bunga, dan tanaman hias." },
        { term: "Plant Selection", explanation: "Proses memilih jenis tanaman yang tepat berdasarkan iklim, tanah, dan tujuan desain." },
        { term: "Site Analysis", explanation: "Evaluasi kondisi lokasi, termasuk topografi, iklim, dan tanah, sebelum merancang." },
        { term: "Sustainability", explanation: "Praktik desain lanskap yang ramah lingkungan dan hemat sumber daya." },
        { term: "Drainage Solutions", explanation: "Sistem untuk mengelola air hujan dan mencegah genangan, seperti saluran atau biopori." },
        { term: "Irrigation Systems", explanation: "Sistem penyiraman otomatis atau manual untuk tanaman." },
        { term: "Native Plants", explanation: "Tanaman asli suatu daerah yang telah beradaptasi dengan lingkungan setempat." },
        { term: "Permaculture", explanation: "Sistem desain pertanian dan sosial yang meniru ekosistem alami." },
        { term: "Hardscape", explanation: "Elemen keras dalam lanskap, seperti jalan setapak, patio, dan dinding penahan." },
        { term: "Water Features", explanation: "Elemen air dalam desain taman, seperti kolam, air mancur, atau air terjun buatan." },
        { term: "Lighting Design", explanation: "Perancangan pencahayaan untuk menonjolkan fitur taman pada malam hari." },
        { term: "Ecological Restoration", explanation: "Proses membantu pemulihan ekosistem yang telah rusak atau hancur." },
        { term: "Garden Structures", explanation: "Bangunan atau struktur di taman, seperti gazebo, pergola, atau teralis." },
        { term: "Topography", explanation: "Bentuk dan kontur permukaan tanah." },
        { term: "Soil Preparation", explanation: "Proses mempersiapkan tanah sebelum menanam, termasuk pemupukan dan penggemburan." },
        { term: "Color Schemes", explanation: "Skema warna yang digunakan dalam pemilihan bunga dan tanaman untuk menciptakan harmoni." },
        { term: "Seasonal Interest", explanation: "Desain taman yang tetap menarik sepanjang tahun dengan pergantian musim." },
        { term: "Focal Points", explanation: "Elemen dalam taman yang dirancang untuk menarik perhatian pertama kali." },
        { term: "Sustainable Materials", explanation: "Penggunaan material ramah lingkungan dan dapat didaur ulang dalam hardscape." },
        { term: "Wildlife Habitat", explanation: "Desain taman yang mendukung kehidupan satwa liar setempat." },
        { term: "Permeable Surfaces", explanation: "Permukaan yang memungkinkan air meresap ke dalam tanah, seperti paving block berpori." },
        { term: "Microclimates", explanation: "Kondisi iklim di area kecil yang berbeda dari lingkungan sekitarnya." },
        { term: "Landscape Architect", explanation: "Profesional yang merancang ruang luar, lanskap, dan taman." },
        { term: "Landscaping Trends", explanation: "Gaya dan ide terbaru dalam desain lanskap." },
        { term: "Drought-Tolerant Plants", explanation: "Tanaman yang membutuhkan sedikit air untuk bertahan hidup." },
        { term: "Organic Gardening", explanation: "Berkebun tanpa menggunakan pestisida dan pupuk kimia sintetis." },
        { term: "Garden Maintenance", explanation: "Kegiatan rutin untuk merawat taman, seperti menyiram, memangkas, dan memupuk." },
        { term: "Outdoor Furniture", explanation: "Perabotan yang dirancang khusus untuk penggunaan di luar ruangan." },
        { term: "Lawn Alternatives", explanation: "Tanaman penutup tanah selain rumput yang membutuhkan lebih sedikit perawatan." },
        { term: "Garden Edging", explanation: "Pembatas antara halaman rumput dan area tanam." },
        { term: "Garden Sculptures", explanation: "Patung atau karya seni yang ditempatkan di taman sebagai hiasan." },
        { term: "Arboriculture", explanation: "Ilmu budidaya, pengelolaan, dan studi pohon dan tanaman berkayu lainnya." },
        { term: "Lawn Care", explanation: "Perawatan halaman rumput, termasuk pemotongan, pemupukan, dan aerasi." },
        { term: "Garden Tools", explanation: "Peralatan yang digunakan untuk berkebun dan merawat taman." },
        { term: "Edible Landscaping", explanation: "Desain taman yang mengintegrasikan tanaman yang dapat dimakan." },
        { term: "Zen Garden", explanation: "Taman kering Jepang yang menggunakan pasir, kerikil, dan batu untuk menciptakan ketenangan." },
        { term: "Container Gardening", explanation: "Menanam tanaman dalam pot atau wadah lainnya." },
        { term: "Coastal Landscaping", explanation: "Desain lanskap untuk area pesisir yang tahan terhadap garam dan angin." },
        { term: "Desert Landscaping", explanation: "Desain lanskap yang menggunakan tanaman tahan kekeringan dan elemen gurun." },
        { term: "Alpine Gardens", explanation: "Taman yang meniru lingkungan pegunungan dengan tanaman tahan dingin." },
        { term: "Formal Gardens", explanation: "Taman dengan desain geometris dan simetris yang teratur." },
        { term: "Rain Gardens", explanation: "Taman yang dirancang untuk menampung dan menyaring air hujan." },
        { term: "Rock Gardens", explanation: "Taman yang menampilkan batu-batuan besar dan tanaman yang tumbuh di celahnya." },
        { term: "Shade Gardens", explanation: "Taman yang dirancang untuk area teduh dengan tanaman yang tahan sedikit cahaya." },
        { term: "Waterwise Gardening", explanation: "Praktik berkebun yang bertujuan untuk menghemat air." },
        { term: "Rooftop Gardens", explanation: "Taman yang dibuat di atap bangunan." },
        { term: "Garden Art", explanation: "Seni atau instalasi yang ditempatkan di taman untuk tujuan estetika." }
    ]},
      { title: "Words/Trigger", keywords: [
        { term: "Serene", explanation: "Menciptakan suasana yang tenang, damai, dan tenteram." },
        { term: "Intense", explanation: "Menghasilkan visual yang kuat, dramatis, dan penuh energi." },
        { term: "Temperature", explanation: "Mengatur nuansa suhu dalam gambar, seperti hangat (warm) atau dingin (cool)." },
        { term: "Atmospheric", explanation: "Menciptakan mood atau suasana tertentu, seringkali dengan kabut, cahaya, atau cuaca." },
        { term: "Highlights", explanation: "Area paling terang dalam gambar yang menangkap cahaya." },
        { term: "Iconic", explanation: "Desain yang sangat terkenal, mudah dikenali, dan menjadi simbol." },
        { term: "Expressions", explanation: "Menampilkan emosi atau karakter, terutama jika ada figur manusia." },
        { term: "Natural", explanation: "Tampak alami, tidak dibuat-buat, dan organik." },
        { term: "Depth", explanation: "Menciptakan ilusi kedalaman dan ruang tiga dimensi dalam gambar." },
        { term: "Texture", explanation: "Menonjolkan kualitas permukaan material dalam gambar." },
        { term: "Symmetry", explanation: "Komposisi yang seimbang dan cermin di kedua sisi sumbu." },
        { term: "Organic", explanation: "Bentuk yang mengalir, tidak teratur, dan terinspirasi dari alam." },
        { term: "Signature", explanation: "Gaya khas atau elemen yang menjadi ciri seorang desainer atau seniman." },
        { term: "Original", explanation: "Desain yang baru, unik, dan belum pernah ada sebelumnya." },
        { term: "Emphatic", explanation: "Menekankan atau menonjolkan elemen tertentu dalam desain." },
        { term: "Masterpiece", explanation: "Menunjukkan karya dengan kualitas artistik dan teknis tertinggi." },
        { term: "Plastic", explanation: "Material sintetis yang dapat dibentuk, sering digunakan dalam desain futuristik atau modern." },
        { term: "Futuristic Style", explanation: "Gaya desain yang membayangkan masa depan, seringkali dengan teknologi canggih dan bentuk aerodinamis." },
        { term: "So Many Details", explanation: "Permintaan untuk gambar yang sangat kaya akan detail kecil dan rumit." },
        { term: "Cinematic Shot", explanation: "Komposisi dan pencahayaan yang meniru gaya sebuah adegan film." },
        { term: "Film Still", explanation: "Gambar tunggal yang terlihat seperti diambil dari sebuah film." },
        { term: "Surreal", explanation: "Visual yang aneh, tidak logis, dan seperti mimpi." },
        { term: "Matrix", explanation: "Estetika yang terinspirasi dari film 'The Matrix', seringkali dengan nuansa hijau, kode digital, dan teknologi distopia." },
        { term: "Norman Foster", explanation: "Arsitek Inggris yang dikenal dengan arsitektur high-tech dan struktur ikonik." },
        { term: "Archdaily", explanation: "Meniru gaya fotografi arsitektur yang ditampilkan di situs web ArchDaily." },
        { term: "Analogue", explanation: "Estetika yang meniru hasil fotografi film analog, seringkali dengan grain dan warna khas." },
        { term: "Sou Fujimoto", explanation: "Arsitek Jepang yang dikenal dengan struktur ringan, transparan, dan konsep 'hutan' arsitektural." },
        { term: "Oscar Niemeyer", explanation: "Arsitek Brasil yang terkenal dengan bentuk-bentuk beton kurva yang sensual dan futuristik." },
        { term: "Architizer", explanation: "Meniru gaya visualisasi arsitektur yang populer di platform Architizer." },
        { term: "Stock Photo", explanation: "Gaya visual yang bersih, cerah, dan umum seperti foto stok komersial." },
        { term: "Professional Camera", explanation: "Meniru kualitas gambar yang dihasilkan oleh kamera profesional." },
        { term: "Overlooking", explanation: "Perspektif yang melihat ke bawah dari titik yang lebih tinggi." },
        { term: "Tilt-Shift Lens", explanation: "Efek lensa yang membuat objek besar terlihat seperti miniatur." },
        { term: "Emphasize", explanation: "Memberikan penekanan pada aspek atau elemen tertentu." },
        { term: "Tranquility", explanation: "Menciptakan perasaan ketenangan dan kedamaian." },
        { term: "Harmony", explanation: "Keseimbangan dan keselarasan antara semua elemen dalam desain." },
        { term: "Pristine", explanation: "Tampilan yang sangat bersih, murni, dan tanpa cela." },
        { term: "Grandeur", explanation: "Kesan kemegahan, kebesaran, dan kemewahan." },
        { term: "Opulent", explanation: "Kaya, mewah, dan berlimpah dengan dekorasi dan material mahal." },
        { term: "Repurposed", explanation: "Menggunakan kembali material atau objek lama untuk fungsi baru." },
        { term: "Reflective Surface", explanation: "Permukaan yang memantulkan cahaya atau lingkungan sekitarnya, seperti cermin atau logam poles." },
        { term: "Serenity", explanation: "Keadaan yang tenang, damai, dan bebas dari gangguan." },
        { term: "Street Road", explanation: "Menampilkan konteks jalan atau lingkungan perkotaan di sekitar bangunan." },
        { term: "Aesthetics", explanation: "Prinsip-prinsip keindahan dan selera artistik yang diterapkan dalam desain." },
        { term: "Stunning", explanation: "Sangat indah atau mengesankan; memukau." }
      ]},
      { title: "Building Material", keywords: [
        { term: "Wood", explanation: "Material alami dari pohon, digunakan untuk struktur, lantai, dan finishing." },
        { term: "Concrete", explanation: "Material komposit dari semen, agregat, dan air, dikenal karena kekuatan dan daya tahannya." },
        { term: "Steel", explanation: "Logam paduan besi dan karbon, digunakan untuk rangka struktural karena kekuatannya." },
        { term: "Brick", explanation: "Blok tanah liat yang dibakar, digunakan untuk dinding dan fasad." },
        { term: "Stone", explanation: "Material alami seperti granit atau marmer, digunakan untuk pondasi, dinding, dan lantai." },
        { term: "Glass", explanation: "Material transparan yang digunakan untuk jendela, dinding tirai, dan partisi." },
        { term: "Asphalt", explanation: "Material berbasis minyak bumi yang digunakan untuk atap dan perkerasan jalan." },
        { term: "Masonry", explanation: "Konstruksi yang menggunakan unit-unit seperti bata, batu, atau balok beton." },
        { term: "Plaster", explanation: "Lapisan penutup dinding atau langit-langit yang halus." },
        { term: "Drywall", explanation: "Papan gipsum yang digunakan untuk membuat dinding dan langit-langit interior." },
        { term: "Fiberglass, Foam Board", explanation: "Material isolasi termal dan akustik." },
        { term: "Shingles, Tiles, Metal Roofing", explanation: "Berbagai jenis material penutup atap." },
        { term: "Hardwood, Laminate, Tile, Carpet", explanation: "Berbagai jenis material penutup lantai." },
        { term: "Vinyl, Aluminum, Fiber Cement", explanation: "Material umum untuk pelapis dinding eksterior (siding)." },
        { term: "Plastic", explanation: "Material sintetis serbaguna untuk pipa, insulasi, dan komponen lainnya." },
        { term: "Cement Board", explanation: "Papan semen yang tahan air, digunakan sebagai alas untuk ubin di area basah." },
        { term: "Plywood", explanation: "Papan kayu lapis yang kuat dan serbaguna." },
        { term: "Reinforced Concrete", explanation: "Beton yang diperkuat dengan tulangan baja untuk menahan gaya tarik." },
        { term: "Timber", explanation: "Kayu yang digunakan sebagai material struktural." },
        { term: "Particleboard", explanation: "Papan yang terbuat dari serpihan kayu yang direkatkan, sering untuk perabotan." },
        { term: "Terrazzo", explanation: "Material lantai komposit dari serpihan marmer atau batu yang dicampur semen atau resin." },
        { term: "Marble", explanation: "Batu alam metamorf dengan pola urat yang khas, digunakan untuk lantai dan permukaan mewah." },
        { term: "Granite", explanation: "Batu beku yang sangat keras dan tahan lama, populer untuk countertop dan lantai." },
        { term: "Quartz", explanation: "Material buatan yang meniru batu alam, sangat tahan gores dan noda." },
        { term: "Sandstone", explanation: "Batu sedimen dengan tekstur berpasir, digunakan untuk dinding dan paving." },
        { term: "Limestone", explanation: "Batu sedimen yang sering mengandung fosil, digunakan untuk fasad dan lantai." },
        { term: "Gypsum Board (Drywall)", explanation: "Nama lain untuk drywall atau papan gipsum." },
        { term: "Rubber", explanation: "Material fleksibel yang digunakan untuk atap, lantai, dan peredam suara." },
        { term: "Clay Tiles", explanation: "Ubin tanah liat yang dibakar, umum digunakan untuk atap dan lantai." },
        { term: "Slate", explanation: "Batu alam yang dapat dibelah tipis, digunakan untuk atap dan lantai premium." },
        { term: "Aluminum Framing", explanation: "Rangka aluminium yang ringan dan tahan karat, sering untuk jendela dan curtain wall." },
        { term: "Composite Decking Materials", explanation: "Material dek luar ruangan yang terbuat dari campuran serat kayu dan plastik." },
        { term: "Electrical Wiring and Conduits", explanation: "Sistem kabel dan pipa pelindung untuk distribusi listrik." },
        { term: "Plumbing Pipes and Fixtures", explanation: "Sistem perpipaan dan perangkat sanitasi untuk air bersih dan kotor." },
        { term: "Fiber-Optic Cables", explanation: "Kabel serat optik untuk transmisi data berkecepatan tinggi." },
        { term: "Paints", explanation: "Cat sebagai lapisan finishing untuk perlindungan dan estetika." },
        { term: "Stucco", explanation: "Lapisan plester eksterior dengan tekstur yang khas." },
        { term: "Bamboo", explanation: "Material rumput raksasa yang berkelanjutan, digunakan untuk lantai, dinding, dan struktur." },
        { term: "Insulated Concrete Forms", explanation: "Cetakan beton permanen yang juga berfungsi sebagai insulasi." },
        { term: "Structural Insulated Panels", explanation: "Panel bangunan prefabrikasi dengan inti insulasi di antara dua lapisan struktural." },
        { term: "Rubberized Roofing Materials", explanation: "Material atap karet yang fleksibel dan tahan air." },
        { term: "Cork", explanation: "Material alami dari kulit pohon ek, digunakan sebagai lantai atau papan dinding karena sifatnya yang empuk dan menyerap suara." },
        { term: "Solar Panels", explanation: "Panel fotovoltaik yang mengubah energi matahari menjadi listrik." }
      ]},
      { title: "Keywords", keywords: [
        { term: "Facade", explanation: "Sisi luar atau 'wajah' sebuah bangunan, terutama bagian depan." },
        { term: "Ventilated Facades", explanation: "Fasad dengan rongga udara di antara lapisan luar dan dinding utama untuk sirkulasi udara dan isolasi." },
        { term: "Glass Curtain Walls", explanation: "Dinding luar non-struktural yang terbuat dari kaca, digantung seperti tirai." },
        { term: "Brick Cladding Facades", explanation: "Fasad dengan lapisan luar dari batu bata." },
        { term: "Stone Cladding", explanation: "Fasad dengan lapisan luar dari lempengan batu alam." },
        { term: "Metal Paneling", explanation: "Fasad yang menggunakan panel-panel logam seperti aluminium atau baja." },
        { term: "Terracotta Facades", explanation: "Fasad yang menggunakan panel atau ubin terakota (tanah liat bakar)." },
        { term: "Sustainable Facades", explanation: "Fasad yang dirancang untuk meningkatkan efisiensi energi dan ramah lingkungan." },
        { term: "Parametric Facades", explanation: "Fasad yang desainnya dihasilkan oleh algoritma komputer, seringkali dengan bentuk kompleks." },
        { term: "Kinetic Facades", explanation: "Fasad yang elemen-elemennya dapat bergerak merespons kondisi lingkungan seperti matahari atau angin." },
        { term: "Green Facades", explanation: "Fasad yang ditutupi oleh tanaman rambat atau 'dinding hidup' (living walls)." },
        { term: "Decorative Facades", explanation: "Fasad yang fungsi utamanya adalah sebagai ornamen atau hiasan." },
        { term: "Digital Screen Facades", explanation: "Fasad yang berfungsi sebagai layar media digital raksasa." },
        { term: "Reflective Facade", explanation: "Fasad dengan material pemantul seperti kaca cermin atau logam poles." },
        { term: "Patterned Facade", explanation: "Fasad yang menampilkan pola visual tertentu melalui material, bentuk, atau warna." },
        { term: "Hybrid Facade", explanation: "Fasad yang menggabungkan beberapa jenis material atau sistem yang berbeda." },
        { term: "Heritage Facade", explanation: "Fasad bangunan bersejarah yang dilestarikan." },
        { term: "Dynamic Facade", explanation: "Fasad yang penampilannya berubah-ubah, bisa karena elemen kinetik atau pencahayaan." },
        { term: "Artistic Facade", explanation: "Fasad yang dirancang sebagai sebuah karya seni." },
        { term: "Prefabricated Facade", explanation: "Fasad yang komponennya dibuat di pabrik dan dipasang di lokasi." },
        { term: "Textile Facade", explanation: "Fasad yang menggunakan material kain atau membran yang diregangkan." },
        { term: "Curtain Wall Facade", explanation: "Sistem fasad non-struktural yang menutupi bangunan, biasanya dari kaca dan aluminium." },
        { term: "Corrugated Metal", explanation: "Lembaran logam bergelombang yang sering digunakan untuk fasad industri atau modern." },
        { term: "Tensile Membrane", explanation: "Struktur membran yang ditarik kencang untuk menciptakan atap atau fasad yang ringan." },
        { term: "Rustic Facade", explanation: "Fasad dengan tampilan pedesaan, sering menggunakan kayu kasar atau batu alam." },
        { term: "Fritted Glass", explanation: "Kaca dengan pola keramik yang dicetak dan dibakar ke permukaannya untuk kontrol visual dan surya." },
        { term: "Bamboo Facade", explanation: "Fasad yang menggunakan bambu sebagai elemen utama." },
        { term: "Solar Facade", explanation: "Fasad yang mengintegrasikan panel surya untuk menghasilkan energi." },
        { term: "Translucent Facade", explanation: "Fasad yang tembus cahaya tetapi tidak transparan, menciptakan efek cahaya yang menyebar." },
        { term: "Perforated Metal", explanation: "Panel logam dengan lubang-lubang berpola untuk menciptakan bayangan, ventilasi, dan estetika." },
        { term: "Timber Facade", explanation: "Fasad yang didominasi oleh penggunaan material kayu." },
        { term: "Geometric Facade", explanation: "Fasad yang menonjolkan bentuk-bentuk geometris yang jelas." },
        { term: "Art Deco Facade", explanation: "Fasad dengan gaya Art Deco, menampilkan pola geometris, simetri, dan ornamen mewah." },
        { term: "Postmodern Facade", explanation: "Fasad dengan gaya Postmodern, seringkali berwarna-warni, eklektik, dan menggunakan referensi historis." },
        { term: "Digital Printed", explanation: "Fasad dengan gambar atau pola yang dicetak secara digital pada materialnya." },
        { term: "Shuttered Concrete", explanation: "Beton yang permukaannya menunjukkan tekstur dari bekisting (cetakan) kayu." },
        { term: "Copper Facade", explanation: "Fasad yang menggunakan panel tembaga, yang seiring waktu akan berubah warna menjadi hijau (patina)." },
        { term: "Mesh Facade", explanation: "Fasad yang menggunakan jaring logam sebagai lapisan luar transparan." },
        { term: "Minimalist Facade", explanation: "Fasad dengan desain yang sangat sederhana, bersih, dan tanpa ornamen." },
        { term: "Industrial Facade", explanation: "Fasad dengan gaya industri, mengekspos material mentah seperti beton, baja, dan bata." },
        { term: "Biophilic Facade", explanation: "Fasad yang mengintegrasikan elemen alam seperti tanaman dan air untuk menghubungkan manusia dengan alam." },
        { term: "Interactive Facade", explanation: "Fasad yang dapat berinteraksi dengan manusia atau lingkungan melalui sensor, cahaya, atau suara." },
        { term: "High-Tech Facade", explanation: "Fasad yang menggunakan teknologi canggih untuk kinerja dan estetika." },
        { term: "Mosaic Facade", explanation: "Fasad yang dihiasi dengan mozaik, yaitu potongan-potongan kecil ubin atau kaca berwarna." }
      ]},
      { title: "Camera/Shot/General", keywords: [
        { term: "One Point Perspective", explanation: "Gambar perspektif dengan satu titik hilang, biasanya saat melihat lurus ke sebuah koridor atau jalan." },
        { term: "Side View", explanation: "Tampak samping dari sebuah objek atau bangunan." },
        { term: "Top View", explanation: "Tampak atas dari sebuah objek, seperti melihat denah." },
        { term: "Front View", explanation: "Tampak depan dari sebuah objek atau bangunan." },
        { term: "Bird's Eye Perspective", explanation: "Pandangan dari atas, seolah-olah dilihat oleh seekor burung yang terbang tinggi." },
        { term: "Aerial Perspective View", explanation: "Pandangan udara yang menunjukkan objek di kejauhan tampak lebih pudar dan kebiruan." },
        { term: "A Top Down Drone View", explanation: "Pandangan lurus ke bawah dari ketinggian, seperti diambil oleh drone." },
        { term: "Aerial View", explanation: "Pandangan umum dari udara atau ketinggian." },
        { term: "One-Point Prespective", explanation: "Ejaan lain untuk One Point Perspective." },
        { term: "Two-Point Prespective", explanation: "Gambar perspektif dengan dua titik hilang, biasanya saat melihat sudut bangunan." },
        { term: "Three-Point Prespective", explanation: "Gambar perspektif dengan tiga titik hilang, untuk pandangan ekstrem ke atas (worm's eye) atau ke bawah (bird's eye)." },
        { term: "Worm-Eye View", explanation: "Pandangan dari bawah ke atas, seolah-olah dilihat oleh cacing." },
        { term: "Distant View", explanation: "Pengambilan gambar dari jarak jauh." },
        { term: "Close Shot", explanation: "Pengambilan gambar dari jarak dekat untuk menunjukkan detail." },
        { term: "Foreground", explanation: "Area yang paling dekat dengan kamera." },
        { term: "Background", explanation: "Area yang paling jauh dari kamera." },
        { term: "Macro Shot", explanation: "Pengambilan gambar sangat dekat untuk detail yang ekstrem." },
        { term: "Wide Shot", explanation: "Pengambilan gambar dengan sudut pandang lebar, mencakup area yang luas." },
        { term: "Telescope", explanation: "Meniru pandangan melalui teleskop, sangat diperbesar dari jarak jauh." },
        { term: "Panoramic Shot", explanation: "Gambar dengan format yang sangat lebar atau tinggi." },
        { term: "35mm", explanation: "Meniru focal length 35mm, sudut pandang yang cukup lebar, umum untuk street photography." },
        { term: "50mm", explanation: "Meniru focal length 50mm, sudut pandang yang mirip dengan mata manusia." },
        { term: "85mm", explanation: "Meniru focal length 85mm, ideal untuk potret dengan latar belakang buram." },
        { term: "135mm", explanation: "Meniru focal length 135mm, telephoto pendek untuk kompresi ruang." },
        { term: "15mm", explanation: "Meniru focal length 15mm, sudut pandang sangat lebar (fisheye atau ultra-wide)." },
        { term: "1/1.4", explanation: "Bukaan lensa (aperture) sangat besar (f/1.4), menghasilkan depth of field yang sangat dangkal." },
        { term: "1/2", explanation: "Bukaan lensa (aperture) besar (f/2)." },
        { term: "f/2.8", explanation: "Bukaan lensa profesional yang serbaguna, menghasilkan latar belakang buram yang bagus." },
        { term: "f/8", explanation: "Bukaan lensa sedang, menghasilkan gambar yang cukup tajam dari depan ke belakang." },
        { term: "f/8-f/16, Architecture", explanation: "Rentang bukaan lensa yang umum digunakan dalam fotografi arsitektur untuk memastikan seluruh bangunan tajam." },
        { term: "Long Shot", explanation: "Pengambilan gambar dari jarak jauh, menunjukkan subjek dalam lingkungannya." },
        { term: "Nikon D5", explanation: "Meniru hasil dari kamera DSLR profesional Nikon D5." },
        { term: "Nikon D3", explanation: "Meniru hasil dari kamera DSLR profesional Nikon D3." },
        { term: "Hasselblad/10X", explanation: "Meniru hasil dari kamera medium format Hasselblad, dikenal dengan kualitas dan detail superior." },
        { term: "Canon Camera", explanation: "Meniru karakteristik umum dari kamera Canon, seringkali dengan reproduksi warna yang hangat." },
        { term: "Shot On iPhone", explanation: "Meniru gaya fotografi dari iPhone, seringkali tajam, cerah, dan kontras." },
        { term: "Shot On Oneplus", explanation: "Meniru gaya fotografi dari smartphone OnePlus." },
        { term: "Fujifilm XT3", explanation: "Meniru hasil dari kamera mirrorless Fujifilm XT3, dikenal dengan simulasi filmnya yang khas." }
      ]},
      { title: "Volume", keywords: [
        { term: "Ambient Light", explanation: "Cahaya umum yang ada di sebuah lingkungan, tanpa sumber yang jelas." },
        { term: "Global", explanation: "Mempengaruhi seluruh adegan atau gambar secara merata." },
        { term: "Light Source", explanation: "Sumber cahaya yang jelas dalam gambar, seperti lampu atau matahari." },
        { term: "Local Soft Light", explanation: "Pencahayaan lembut yang hanya menerangi area tertentu." },
        { term: "Fluorescent Light", explanation: "Cahaya dari lampu neon, seringkali dengan nuansa sedikit kehijauan atau kebiruan." },
        { term: "Morning Light", explanation: "Cahaya matahari pagi, biasanya lembut dan berwarna hangat." },
        { term: "Top Light", explanation: "Pencahayaan yang datang dari atas subjek." },
        { term: "Crepuscular Rays", explanation: "Sinar matahari yang terlihat menembus celah awan, sering disebut 'sinar Tuhan'." },
        { term: "Global Illumination", explanation: "Simulasi realistis tentang bagaimana cahaya memantul dari permukaan ke permukaan lain." },
        { term: "Cold Light", explanation: "Cahaya dengan temperatur warna kebiruan, menciptakan suasana sejuk atau dingin." },
        { term: "Volumetric", explanation: "Cahaya yang terlihat memiliki volume atau massa, seperti sinar yang menembus kabut atau debu." },
        { term: "Incandescence", explanation: "Cahaya yang dipancarkan oleh benda yang sangat panas, seperti pijar lampu." },
        { term: "Raking Light", explanation: "Cahaya yang menyinari permukaan dari sudut yang sangat rendah, menonjolkan tekstur." },
        { term: "Edge Light", explanation: "Cahaya yang menerangi tepi subjek dari belakang, memisahkannya dari latar belakang." },
        { term: "Backlight", explanation: "Cahaya yang datang dari belakang subjek, seringkali menciptakan siluet." },
        { term: "Hard Light", explanation: "Cahaya dari sumber kecil dan langsung, menciptakan bayangan yang tajam dan kontras tinggi." },
        { term: "Sun Light", explanation: "Cahaya alami dari matahari." },
        { term: "Golden Hour Light", explanation: "Cahaya matahari hangat dan keemasan sesaat setelah matahari terbit atau sebelum terbenam." },
        { term: "Cool Light", explanation: "Sama dengan 'Cold Light', cahaya dengan nuansa kebiruan." },
        { term: "Warm Light", explanation: "Cahaya dengan temperatur warna kekuningan atau kemerahan, menciptakan suasana hangat dan nyaman." },
        { term: "Room Light", explanation: "Pencahayaan buatan di dalam sebuah ruangan." },
        { term: "Chiaroscuro Light", explanation: "Kontras dramatis antara area terang dan gelap dalam sebuah gambar." },
        { term: "Reflect Light", explanation: "Cahaya yang dipantulkan dari sebuah permukaan." },
        { term: "Mapping Light", explanation: "Penggunaan cahaya untuk mendefinisikan bentuk dan volume suatu objek." },
        { term: "Hierarchical Light", explanation: "Penggunaan tingkat kecerahan yang berbeda untuk memandu mata dan menunjukkan kepentingan." },
        { term: "Flood Light", explanation: "Cahaya yang menyebar luas untuk menerangi area yang besar." },
        { term: "Glowing Light", explanation: "Cahaya yang tampak bersinar lembut dari dalam suatu objek." },
        { term: "Laser Light", explanation: "Sinar cahaya yang sangat terfokus dan lurus." },
        { term: "Warm White Light", explanation: "Cahaya putih dengan sedikit nuansa kekuningan, umum untuk interior." },
        { term: "Film Lighting", explanation: "Pencahayaan dramatis yang meniru gaya sinematografi film." },
        { term: "Cool Lighting", explanation: "Pencahayaan dengan nuansa warna sejuk (biru, hijau)." },
        { term: "Mood Lighting", explanation: "Pencahayaan yang dirancang untuk menciptakan suasana atau mood tertentu." },
        { term: "Moonlight", explanation: "Cahaya lembut dan dingin dari bulan." }
      ]},
      { title: "Buildings/Highrise", keywords: [
        { term: "Architecture", explanation: "Seni dan ilmu merancang dan membangun bangunan." },
        { term: "Tall Buildings", explanation: "Bangunan yang tingginya melebihi bangunan sekitarnya secara signifikan." },
        { term: "Urban Architecture", explanation: "Arsitektur yang dirancang dalam konteks perkotaan yang padat." },
        { term: "High-Density Development", explanation: "Pembangunan dengan rasio jumlah unit atau luas lantai yang tinggi terhadap luas lahan." },
        { term: "Vertical Construction", explanation: "Proses membangun ke atas untuk memaksimalkan penggunaan lahan." },
        { term: "Towering Structures", explanation: "Struktur yang menjulang sangat tinggi." },
        { term: "Architectural Landmarks", explanation: "Bangunan yang menjadi ikon atau penanda suatu kota atau daerah." },
        { term: "Modern Skyscrapers", explanation: "Pencakar langit dengan desain modern, seringkali menggunakan kaca dan baja." },
        { term: "Iconic Skyscrapers", explanation: "Pencakar langit yang sangat terkenal dan menjadi simbol, seperti Burj Khalifa atau Empire State Building." },
        { term: "Tall Towers", explanation: "Menara tinggi, bisa berupa gedung perkantoran, hunian, atau observasi." },
        { term: "Skyscraper Features", explanation: "Elemen khas pencakar langit, seperti puncak menara (spire), setback, atau fasad kaca." },
        { term: "Steel and Concrete Towers", explanation: "Menara yang dibangun dengan struktur utama baja dan beton." },
        { term: "Glass Facades", explanation: "Fasad bangunan tinggi yang didominasi oleh material kaca." },
        { term: "High-Rise Designs", explanation: "Rancangan arsitektur untuk bangunan-bangunan tinggi." },
        { term: "Urban Skyscrapers", explanation: "Pencakar langit yang berada di pusat kota yang padat." },
        { term: "Vertical Living", explanation: "Konsep tinggal di apartemen atau hunian di gedung-gedung tinggi." },
        { term: "Residential Skyscrapers", explanation: "Pencakar langit yang fungsi utamanya adalah sebagai tempat tinggal." },
        { term: "Commercial Towers", explanation: "Menara yang digunakan untuk perkantoran, ritel, atau kegiatan komersial lainnya." },
        { term: "High-Rise Apartments", explanation: "Unit-unit apartemen yang berada di dalam gedung tinggi." },
        { term: "Sky-High Structures", explanation: "Struktur yang mencapai ketinggian yang sangat ekstrem." },
        { term: "City Skylines", explanation: "Garis horizon visual dari sebuah kota yang dibentuk oleh gedung-gedungnya." },
        { term: "High-Rise Construction", explanation: "Teknik dan proses pembangunan gedung-gedung tinggi." },
        { term: "Megatall Buildings", explanation: "Bangunan dengan ketinggian di atas 600 meter." },
        { term: "Urban Development Projects", explanation: "Proyek-proyek pembangunan skala besar di area perkotaan." },
        { term: "Engineering Marvels", explanation: "Struktur yang dianggap sebagai keajaiban teknik karena desain dan konstruksinya yang luar biasa." },
        { term: "Futuristic Towers", explanation: "Menara dengan desain yang inovatif dan membayangkan masa depan." }
      ]},
      { title: "Drawing Styles", keywords: [
        { term: "Classic Drawing Style", explanation: "Gaya gambar yang mengacu pada tradisi seni klasik Yunani dan Romawi, menekankan realisme dan proporsi ideal." },
        { term: "Pop Art", explanation: "Gaya seni yang terinspirasi dari budaya populer dan iklan, dengan warna-warna cerah dan kontras tinggi." },
        { term: "Sketching", explanation: "Gambar cepat dan kasar untuk menangkap ide atau bentuk dasar." },
        { term: "Photorealism/Hyperrealism", explanation: "Gaya gambar yang bertujuan untuk mereplikasi foto sedetail mungkin." },
        { term: "Doodling", explanation: "Gambar spontan dan tidak terfokus yang dibuat sambil melamun." },
        { term: "Comic Drawing Style", explanation: "Gaya gambar seperti dalam buku komik, dengan garis tebal dan warna solid." },
        { term: "Manga", explanation: "Gaya komik Jepang yang khas dengan mata besar dan ekspresi dramatis." },
        { term: "Cartoon", explanation: "Gaya gambar yang disederhanakan dan seringkali dilebih-lebihkan untuk humor." },
        { term: "Fantasy Art", explanation: "Seni yang menggambarkan subjek magis, mitologis, atau supernatural." },
        { term: "Anamorphic", explanation: "Gambar terdistorsi yang hanya terlihat normal dari sudut pandang tertentu." },
        { term: "Charcoal Drawing", explanation: "Gambar yang dibuat dengan arang, menghasilkan kontras yang kuat dan tekstur lembut." },
        { term: "Ballpoint Pen Drawing Style", explanation: "Gambar yang dibuat dengan pulpen, seringkali dengan teknik arsiran silang (cross-hatching)." },
        { term: "Stippling/Pointillism", explanation: "Teknik menciptakan gambar dengan menggunakan titik-titik kecil." },
        { term: "Impressionism", explanation: "Gaya seni yang menekankan kesan cahaya dan warna sesaat, seringkali dengan sapuan kuas yang terlihat." },
        { term: "Surrealism", explanation: "Gaya seni yang mengeksplorasi alam bawah sadar, menghasilkan citra aneh dan seperti mimpi." },
        { term: "Architectural Drawing", explanation: "Gambar teknis atau artistik dari sebuah bangunan." },
        { term: "Cubism", explanation: "Gaya seni yang memecah objek menjadi bentuk-bentuk geometris dan menampilkannya dari berbagai sudut pandang sekaligus." },
        { term: "Realism", explanation: "Upaya untuk menggambarkan subjek secara akurat dan sesuai dengan kenyataan." },
        { term: "Art Nouveau Drawing Style", explanation: "Gaya dekoratif yang terinspirasi dari bentuk organik dan garis-garis melengkung yang mengalir." },
        { term: "Renaissance and Neo", explanation: "Mengacu pada gaya seni periode Renaisans (abad 14-16) dan kebangkitannya kembali (Neo-Renaisans)." },
        { term: "Modern Art", explanation: "Gerakan seni dari akhir abad ke-19 hingga pertengahan abad ke-20 yang menolak tradisi dan bereksperimen dengan bentuk dan warna." },
        { term: "Chinese Brush Painting", explanation: "Lukisan tradisional Tiongkok yang menggunakan kuas, tinta, dan kertas khusus, dengan penekanan pada sapuan kuas yang ekspresif." },
        { term: "Japanese Sumi-e", explanation: "Lukisan tinta monokromatik Jepang yang menekankan keindahan dalam kesederhanaan dan sapuan kuas." },
        { term: "Persian Miniature Painting", explanation: "Lukisan kecil yang sangat detail dari Persia, seringkali mengilustrasikan manuskrip." },
        { term: "Indian Madhubani Painting", explanation: "Seni rakyat dari India yang ditandai dengan pola geometris yang rumit dan warna-warna cerah." },
        { term: "Islamic Calligraphy", explanation: "Seni menulis Arab yang indah, sering digunakan sebagai elemen dekoratif dalam arsitektur dan seni Islam." },
        { term: "European Renaissance", explanation: "Seni dari periode Renaisans di Eropa, menekankan humanisme, realisme, dan perspektif." },
        { term: "Abstract Expressionism", explanation: "Gerakan seni pasca-Perang Dunia II yang menekankan ekspresi emosional spontan melalui sapuan kuas yang kuat." },
        { term: "African Tribal Art", explanation: "Beragam seni dari berbagai suku di Afrika, seringkali berupa patung dan topeng dengan bentuk stilisasi." },
        { term: "Indigenous Australian Art", explanation: "Seni dari penduduk asli Australia, seringkali menggunakan titik-titik (dot painting) dan simbol-simbol sakral." },
        { term: "Mexican Muralism", explanation: "Lukisan dinding skala besar di Meksiko yang seringkali bertema sosial dan politik." },
        { term: "Banksy/Street Art", explanation: "Gaya seni yang dibuat di ruang publik, seringkali dengan pesan politis atau satir, meniru gaya seniman jalanan Banksy." },
        { term: "Digital Art", explanation: "Seni yang dibuat menggunakan perangkat lunak dan perangkat digital." }
      ]},
      { title: "Negative", keywords: [
        { term: "Text", explanation: "Meminta AI untuk tidak menghasilkan teks, huruf, atau tulisan apa pun di dalam gambar." },
        { term: "Cropped", explanation: "Meminta agar subjek utama tidak terpotong di tepi gambar." },
        { term: "Low Quality", explanation: "Menghindari hasil gambar dengan kualitas rendah." },
        { term: "Normal Quality", explanation: "Menghindari hasil gambar dengan kualitas standar atau rata-rata." },
        { term: "Username", explanation: "Mencegah AI menambahkan nama pengguna atau identitas pembuat." },
        { term: "Watermark", explanation: "Mencegah munculnya tanda air atau logo di atas gambar." },
        { term: "Signature", explanation: "Mencegah AI menambahkan tanda tangan artis atau pembuat." },
        { term: "Blurry", explanation: "Menghindari gambar yang buram atau tidak fokus." },
        { term: "Soft", explanation: "Menghindari gambar yang kurang tajam atau terlalu lembut." },
        { term: "Outline", explanation: "Menghindari garis tepi yang tebal atau tidak natural di sekitar objek." },
        { term: "Current Line", explanation: "Istilah yang kurang umum, kemungkinan untuk menghindari artefak garis tertentu." },
        { term: "Ugly", explanation: "Mencegah hasil yang secara estetika tidak menyenangkan." },
        { term: "Logo", explanation: "Menghindari munculnya logo merek atau perusahaan." },
        { term: "Pixelated", explanation: "Menghindari gambar yang pecah atau berpiksel kasar." },
        { term: "Lowres", explanation: "Singkatan dari 'low resolution', menghindari gambar beresolusi rendah." },
        { term: "Medium_Filesize", explanation: "Menghindari gambar dengan ukuran file sedang, menyiratkan kualitas yang lebih tinggi." },
        { term: "Small_Filesize", explanation: "Menghindari gambar dengan ukuran file kecil, menyiratkan kualitas yang lebih tinggi." },
        { term: "Tiling", explanation: "Mencegah munculnya pola berulang atau ubin yang tidak diinginkan." },
        { term: "Out Of Frame", explanation: "Meminta agar semua elemen penting berada di dalam bingkai gambar." },
        { term: "Disfigured", explanation: "Menghindari bentuk yang rusak atau cacat, terutama pada anatomi." },
        { term: "Deformed", explanation: "Menghindari objek atau figur dengan bentuk yang tidak normal." },
        { term: "Duplicate", explanation: "Menghindari adanya objek yang sama terduplikasi secara tidak wajar." },
        { term: "Low Resolution", explanation: "Ejaan lengkap untuk 'lowres', menghindari gambar resolusi rendah." },
        { term: "Saturated", explanation: "Menghindari warna yang terlalu pekat atau jenuh." }
      ]},
    ],
  },
  {
    collectionTitle: "Building Types",
    categories: [
        { title: "Residential Buildings", keywords: [
          { term: "Single-Family Homes", explanation: "Rumah tinggal tunggal yang berdiri sendiri di atas sebidang tanah." },
          { term: "Duplex", explanation: "Satu bangunan yang dibagi menjadi dua unit tempat tinggal terpisah." },
          { term: "Townhouses", explanation: "Rumah deret yang berbagi satu atau dua dinding dengan unit tetangga." },
          { term: "Condominiums (Condos)", explanation: "Unit apartemen yang dimiliki secara individual dalam sebuah bangunan dengan fasilitas bersama." },
          { term: "Apartment Complexes", explanation: "Sebuah bangunan atau sekelompok bangunan yang berisi banyak unit apartemen untuk disewa." },
          { term: "Co-Housing Communities", explanation: "Komunitas perumahan di mana penduduk memiliki rumah pribadi tetapi berbagi fasilitas umum yang luas." },
          { term: "Manufactured Homes", explanation: "Rumah yang dibangun di pabrik dan kemudian diangkut ke lokasi." },
          { term: "Retirement Communities", explanation: "Kompleks perumahan yang dirancang khusus untuk orang lanjut usia." },
          { term: "Multi-Family Housing", explanation: "Bangunan yang dirancang untuk menampung lebih dari satu keluarga, seperti duplex atau apartemen." },
          { term: "Vacation Homes", explanation: "Rumah kedua yang digunakan untuk liburan atau rekreasi." },
          { term: "Affordable Housing", explanation: "Perumahan yang ditujukan bagi individu atau keluarga dengan pendapatan rendah hingga menengah." },
          { term: "Luxury Residences", explanation: "Hunian mewah dengan fasilitas dan finishing berkualitas tinggi." },
          { term: "Housing Developments", explanation: "Area perumahan skala besar yang direncanakan dan dibangun oleh pengembang." },
          { term: "Eco-Friendly Housing", explanation: "Perumahan yang dirancang dan dibangun dengan prinsip ramah lingkungan." },
          { term: "Smart Homes", explanation: "Rumah yang dilengkapi dengan teknologi otomatisasi untuk mengontrol pencahayaan, suhu, dan keamanan." },
          { term: "Prefabricated Houses", explanation: "Rumah yang komponennya dibuat di pabrik sebelum dirakit di lokasi (pre-fab)." },
          { term: "Tiny Houses", explanation: "Rumah berukuran sangat kecil, biasanya di bawah 40 meter persegi, yang mengedepankan kesederhanaan." },
          { term: "Bungalows", explanation: "Rumah satu lantai, seringkali dengan beranda dan atap landai." },
          { term: "Mansions", explanation: "Rumah yang sangat besar dan mewah." },
          { term: "Housing Cooperatives", explanation: "Bentuk kepemilikan di mana penduduk secara kolektif memiliki bangunan dan membeli saham untuk hak tinggal di satu unit." }
        ]},
        { title: "Educational Buildings", keywords: [
          { term: "Colleges", explanation: "Institusi pendidikan tinggi yang menawarkan gelar sarjana." },
          { term: "Universities", explanation: "Institusi pendidikan tinggi besar yang terdiri dari beberapa fakultas dan menawarkan program sarjana hingga doktoral." },
          { term: "Schools (K-12)", explanation: "Sekolah untuk pendidikan dasar dan menengah (Taman Kanak-kanak hingga kelas 12)." },
          { term: "Preschools", explanation: "Sekolah untuk anak-anak usia dini sebelum masuk taman kanak-kanak." },
          { term: "Daycare Centers", explanation: "Fasilitas penitipan anak." },
          { term: "Vocational Schools", explanation: "Sekolah yang memberikan pelatihan untuk keterampilan atau pekerjaan tertentu." },
          { term: "Trade Schools", explanation: "Sekolah kejuruan yang fokus pada pelatihan teknis untuk perdagangan seperti pertukangan atau otomotif." },
          { term: "Montessori Schools", explanation: "Sekolah yang menggunakan metode pendidikan Montessori, menekankan kemandirian anak." },
          { term: "Boarding Schools", explanation: "Sekolah di mana siswanya tinggal di asrama selama masa sekolah." },
          { term: "International Schools", explanation: "Sekolah yang menawarkan kurikulum internasional, seringkali untuk siswa ekspatriat." },
          { term: "Special Education Schools", explanation: "Sekolah yang dirancang untuk siswa dengan kebutuhan pendidikan khusus." },
          { term: "Online Education Platforms", explanation: "Platform digital yang menyediakan kursus dan program pendidikan secara online." },
          { term: "Campus Facilities", explanation: "Semua fasilitas yang ada di area kampus, seperti ruang kelas, perpustakaan, dan laboratorium." },
          { term: "School Districts", explanation: "Wilayah administratif yang mengelola sekolah-sekolah negeri di suatu area." },
          { term: "Auditoriums", explanation: "Ruang besar untuk pertunjukan, kuliah, atau pertemuan." },
          { term: "Libraries", explanation: "Gedung atau ruangan tempat koleksi buku dan sumber informasi lainnya disimpan." },
          { term: "Laboratories", explanation: "Ruangan yang dilengkapi peralatan untuk penelitian atau eksperimen ilmiah." },
          { term: "Gymnasiums", explanation: "Ruang atau gedung besar untuk kegiatan olahraga dalam ruangan." },
          { term: "Dormitories", explanation: "Asrama tempat tinggal mahasiswa atau siswa." },
          { term: "Administrative Buildings", explanation: "Gedung yang digunakan untuk kantor administrasi atau tata usaha." }
        ]},
        { title: "Commercial", keywords: [
          { term: "Office Buildings", explanation: "Gedung yang digunakan sebagai ruang kerja atau perkantoran." },
          { term: "Retail Stores", explanation: "Toko yang menjual barang langsung ke konsumen." },
          { term: "Shopping Malls", explanation: "Pusat perbelanjaan besar yang menampung berbagai macam toko ritel." },
          { term: "Restaurants", explanation: "Tempat usaha yang menyajikan makanan dan minuman." },
          { term: "Hotels", explanation: "Bangunan yang menyediakan penginapan, makanan, dan layanan lainnya untuk wisatawan." },
          { term: "Banks", explanation: "Institusi keuangan yang menyediakan layanan perbankan." },
          { term: "Warehouses", explanation: "Gudang besar untuk menyimpan barang." },
          { term: "Industrial Facilities", explanation: "Fasilitas yang digunakan untuk produksi, manufaktur, atau kegiatan industri lainnya." },
          { term: "Factories", explanation: "Pabrik tempat barang diproduksi secara massal." },
          { term: "Convention Centers", explanation: "Fasilitas besar untuk menyelenggarakan pameran, konferensi, dan acara besar." },
          { term: "Theaters", explanation: "Gedung untuk pertunjukan seni seperti drama, musik, atau film." },
          { term: "Sports Arenas", explanation: "Arena besar untuk pertandingan olahraga dan konser." },
          { term: "Gas Stations", explanation: "Stasiun pengisian bahan bakar untuk kendaraan." },
          { term: "Convenience Stores", explanation: "Toko kecil yang menjual kebutuhan sehari-hari." },
          { term: "Car Dealerships", explanation: "Tempat penjualan mobil baru atau bekas." },
          { term: "Showrooms", explanation: "Ruang pamer untuk menampilkan produk seperti mobil, furnitur, atau pakaian." },
          { term: "Skyscrapers", explanation: "Gedung pencakar langit yang sangat tinggi, biasanya untuk perkantoran atau penggunaan campuran." },
          { term: "Mixed-Use Developments", explanation: "Pembangunan yang menggabungkan beberapa fungsi, seperti ritel, perkantoran, dan hunian, dalam satu kompleks." },
          { term: "Business Parks", explanation: "Kawasan yang dikembangkan khusus untuk perkantoran dan bisnis." },
          { term: "Data Centers", explanation: "Fasilitas yang menampung server komputer dan infrastruktur data." }
        ]},
        { title: "Healthcare Buildings", keywords: [
          { term: "Hospitals", explanation: "Institusi perawatan kesehatan yang menyediakan pengobatan pasien dengan staf medis khusus dan peralatan." },
          { term: "Clinics", explanation: "Fasilitas kesehatan yang lebih kecil dari rumah sakit, seringkali untuk perawatan rawat jalan." },
          { term: "Medical Offices", explanation: "Kantor praktik dokter atau spesialis medis." },
          { term: "Nursing Homes", explanation: "Panti jompo yang menyediakan perawatan jangka panjang untuk lansia." },
          { term: "Rehabilitation Centers", explanation: "Pusat rehabilitasi untuk pemulihan dari cedera, penyakit, atau kecanduan." },
          { term: "Urgent Care Facilities", explanation: "Fasilitas gawat darurat untuk kondisi medis yang tidak mengancam jiwa." },
          { term: "Ambulatory Surgery Centers", explanation: "Pusat bedah rawat jalan untuk prosedur yang tidak memerlukan rawat inap." },
          { term: "Hospice Centers", explanation: "Pusat perawatan paliatif untuk pasien stadium akhir." },
          { term: "Imaging Centers", explanation: "Pusat diagnostik yang menyediakan layanan pencitraan medis seperti X-ray dan MRI." },
          { term: "Veterinary Clinics", explanation: "Klinik untuk perawatan kesehatan hewan." },
          { term: "Pharmacies", explanation: "Apotek tempat menjual obat-obatan." },
          { term: "Dental Clinics", explanation: "Klinik untuk perawatan gigi dan mulut." },
          { term: "Research Laboratories", explanation: "Laboratorium untuk penelitian medis dan ilmiah." },
          { term: "Blood Banks", explanation: "Bank darah untuk penyimpanan dan distribusi darah." },
          { term: "Behavioral Health Facilities", explanation: "Fasilitas untuk perawatan kesehatan mental dan perilaku." }
        ]},
        { title: "Government Buildings", keywords: [
          { term: "Courthouses", explanation: "Gedung pengadilan tempat proses hukum berlangsung." },
          { term: "City Halls", explanation: "Balai kota, pusat administrasi pemerintahan kota." },
          { term: "State Capitols", explanation: "Gedung pusat pemerintahan negara bagian." },
          { term: "Federal Buildings", explanation: "Gedung yang menampung kantor-kantor pemerintahan federal atau pusat." },
          { term: "Police Stations", explanation: "Kantor polisi." },
          { term: "Fire Stations", explanation: "Pos pemadam kebakaran." },
          { term: "Prisons", explanation: "Lembaga pemasyarakatan atau penjara." },
          { term: "Post Offices", explanation: "Kantor pos untuk layanan surat-menyurat dan paket." },
          { term: "Military Bases", explanation: "Pangkalan militer." },
          { term: "Embassies", explanation: "Kantor perwakilan diplomatik suatu negara di negara lain." },
          { term: "Consulates", explanation: "Kantor perwakilan konsuler suatu negara di kota lain di negara asing." },
          { term: "Government Offices", explanation: "Kantor-kantor yang digunakan oleh lembaga pemerintah." },
          { term: "Civic Centers", explanation: "Pusat kegiatan sipil dan budaya milik pemerintah." },
          { term: "Public Libraries", explanation: "Perpustakaan yang terbuka untuk umum dan didanai oleh pemerintah." },
          { term: "Municipal Facilities", explanation: "Fasilitas milik pemerintah kota, seperti fasilitas pengelolaan air atau sampah." }
        ]},
        { title: "Religious", keywords: [
          { term: "Churches", explanation: "Gereja, tempat ibadah umat Kristen." },
          { term: "Cathedrals", explanation: "Katedral, gereja utama dalam sebuah keuskupan yang menjadi pusat kedudukan uskup." },
          { term: "Mosques", explanation: "Masjid, tempat ibadah umat Islam." },
          { term: "Synagogues", explanation: "Sinagoge, tempat ibadah umat Yahudi." },
          { term: "Temples", explanation: "Kuil atau candi, tempat ibadah untuk berbagai agama seperti Hindu, Buddha, atau Shinto." },
          { term: "Shrines", explanation: "Tempat suci atau keramat yang didedikasikan untuk dewa, orang suci, atau tokoh yang dihormati." },
          { term: "Monasteries", explanation: "Biara, tempat tinggal komunitas biarawan atau biarawati." },
          { term: "Chapels", explanation: "Kapel, ruang ibadah kecil, bisa berdiri sendiri atau di dalam bangunan yang lebih besar." },
          { term: "Religious Retreats", explanation: "Tempat untuk retret atau kontemplasi keagamaan." },
          { term: "Religious Schools", explanation: "Sekolah yang berafiliasi dengan agama tertentu." },
          { term: "Meditation Centers", explanation: "Pusat untuk praktik meditasi." },
          { term: "Spiritual Retreats", explanation: "Tempat peristirahatan untuk kegiatan spiritual." },
          { term: "Meeting Halls", explanation: "Aula pertemuan yang digunakan oleh kelompok-kelompok keagamaan." },
          { term: "Worship Centers", explanation: "Pusat ibadah atau tempat pemujaan." }
        ]},
        { title: "Recreational", keywords: [
          { term: "Sports Complexes", explanation: "Kompleks olahraga dengan berbagai fasilitas untuk beberapa cabang olahraga." },
          { term: "Fitness Centers", explanation: "Pusat kebugaran atau gym." },
          { term: "Swimming Pools", explanation: "Kolam renang untuk olahraga atau rekreasi." },
          { term: "Community Centers", explanation: "Pusat kegiatan masyarakat yang menyediakan berbagai program rekreasi dan sosial." },
          { term: "Recreation Centers", explanation: "Pusat rekreasi yang menawarkan berbagai aktivitas hiburan dan olahraga." },
          { term: "Theatres", explanation: "Gedung pertunjukan untuk teater, opera, atau konser." },
          { term: "Art Galleries", explanation: "Galeri seni untuk memamerkan karya seni visual." },
          { term: "Museums", explanation: "Museum untuk memamerkan koleksi benda-benda bersejarah, seni, atau ilmiah." },
          { term: "Aquariums", explanation: "Akuarium publik untuk memamerkan kehidupan laut." },
          { term: "Amusement Parks", explanation: "Taman hiburan dengan berbagai wahana permainan dan atraksi." },
          { term: "Stadiums", explanation: "Stadion besar untuk pertandingan olahraga, terutama di luar ruangan." },
          { term: "Arenas", explanation: "Arena besar untuk olahraga atau acara hiburan, biasanya di dalam ruangan." },
          { term: "Skating Rinks", explanation: "Arena untuk seluncur es atau sepatu roda." },
          { term: "Bowling Alleys", explanation: "Tempat untuk bermain boling." },
          { term: "Golf Courses", explanation: "Lapangan golf." }
        ]}
    ]
  },
  {
    collectionTitle: "Architecture Styles",
    categories: [
      {
        title: "Styles",
        keywords: [
          { term: "Neolithic Architecture", explanation: "Arsitektur prasejarah yang menggunakan batu-batu besar (megalit) seperti Stonehenge." },
          { term: "Architecture of Mesopotamia (Sumerian)", explanation: "Arsitektur kuno di Mesopotamia (sekarang Irak) yang ditandai dengan ziggurat (piramida bertingkat) dan penggunaan bata lumpur." },
          { term: "Ancient Egyptian Architecture", explanation: "Arsitektur Mesir kuno yang monumental, terkenal dengan piramida, kuil, dan makam yang megah." },
          { term: "Mesoamerican Architecture", explanation: "Arsitektur peradaban kuno di Amerika Tengah (Maya, Aztec) yang mencakup piramida berundak dan istana batu." },
          { term: "Architecture of Mesopotamia (Assyrian)", explanation: "Gaya arsitektur Asiria kuno yang menampilkan istana-istana besar dengan relief batu yang menggambarkan adegan perang dan perburuan." },
          { term: "Ancient Greek Architecture", explanation: "Arsitektur Yunani kuno yang menekankan keteraturan, proporsi, dan sistem kolom (Doric, Ionic, Corinthian), seperti Parthenon." },
          { term: "Ancient Roman Architecture", explanation: "Arsitektur Romawi kuno yang mengembangkan penggunaan lengkungan, kubah, dan beton, seperti Colosseum dan Pantheon." },
          { term: "Petrine Baroque (Russia)", explanation: "Gaya Baroque Rusia pada masa Peter yang Agung, lebih terkendali dan dipengaruhi oleh arsitektur Eropa Barat." },
          { term: "Moorish Architecture", explanation: "Arsitektur Islam di Afrika Utara dan Spanyol yang kaya akan detail geometris, ubin warna-warni (azulejos), dan lengkungan tapal kuda." },
          { term: "Architecture of Kievan Rus'", explanation: "Arsitektur negara Slavia timur abad pertengahan yang dipengaruhi oleh Bizantium, ditandai dengan gereja berkubah bawang." },
          { term: "Romanesque Architecture", explanation: "Gaya arsitektur Eropa abad pertengahan (abad 11-12) dengan dinding tebal, jendela kecil, dan lengkungan setengah lingkaran." },
          { term: "Norman Architecture", explanation: "Variasi arsitektur Romanesque yang berkembang di Normandia dan Inggris, ditandai dengan skala besar dan dekorasi geometris." },
          { term: "Mudéjar Art", explanation: "Gaya seni dan arsitektur di Spanyol yang memadukan tradisi Kristen dengan pengaruh Islam (Moorish)." },
          { term: "Gothic Architecture", explanation: "Gaya arsitektur Eropa abad pertengahan (abad 12-16) yang ditandai dengan lengkungan runcing, kubah rusuk, dan penopang layang (flying buttress)." },
          { term: "Early Muscovite Architecture (Russia)", explanation: "Arsitektur Moskow awal (abad 14-15) yang mengembangkan gaya gereja kubah bawang yang khas." },
          { term: "Vijayanagara Architecture", explanation: "Gaya arsitektur Kerajaan Vijayanagara di India Selatan, dikenal dengan kuil-kuil batu yang rumit dan mandapa (aula berkolom)." },
          { term: "Sondergotik (Special Gothic)", explanation: "Gaya Gotik Akhir di Jerman dan Eropa Tengah yang menampilkan kubah jaring (net vault) yang sangat rumit." },
          { term: "Renaissance Architecture", explanation: "Gaya arsitektur yang lahir kembali di Italia pada abad ke-15, menekankan simetri, proporsi, dan elemen klasik Yunani-Romawi." },
          { term: "Tudor Architecture", explanation: "Gaya arsitektur Inggris pada masa Dinasti Tudor, ditandai dengan konstruksi setengah kayu (half-timber) dan jendela Oriel." },
          { term: "Manueline", explanation: "Gaya Gotik Akhir Portugis yang sangat ornamental, dengan motif maritim seperti tali, karang, dan bola dunia." },
          { term: "High Renaissance", explanation: "Puncak arsitektur Renaisans (awal abad ke-16) yang ditandai dengan harmoni dan keseimbangan sempurna, karya Bramante dan Raphael." },
          { term: "Mannerism (Late Renaissance)", explanation: "Gaya Renaisans Akhir yang bermain dengan aturan klasik, seringkali dengan proporsi yang aneh dan kompleksitas yang disengaja." },
          { term: "Purism (Spanish Architecture)", explanation: "Gaya Renaisans Spanyol yang lebih sederhana dan murni, sebagai reaksi terhadap gaya Plateresque yang ornamental." },
          { term: "Middle Muscovite Architecture (Russia)", explanation: "Arsitektur Moskow pertengahan (abad 16) yang menampilkan gereja-gereja tenda yang unik, seperti Katedral St. Basil." },
          { term: "Mughal Architecture (Indo-Islamic)", explanation: "Gaya arsitektur kekaisaran Mughal di India yang megah, simetris, dan indah, contohnya Taj Mahal." },
          { term: "Herrerian Style Architecture", explanation: "Gaya arsitektur Spanyol akhir abad ke-16 yang sangat sederhana, geometris, dan monumental, dinamai dari arsitek Juan de Herrera." },
          { term: "Baroque Architecture", explanation: "Gaya arsitektur abad ke-17 yang dramatis, emosional, dan mewah, dengan bentuk-bentuk melengkung dan ornamen yang kaya." },
          { term: "Palladian Architecture", explanation: "Gaya arsitektur yang terinspirasi oleh arsitek Italia Andrea Palladio, menekankan simetri, perspektif, dan nilai-nilai klasik." },
          { term: "Naryshkin Baroque (Moscow)", explanation: "Gaya Baroque Moskow akhir abad ke-17 yang memadukan tradisi Rusia dengan elemen Baroque dari Eropa Tengah." },
          { term: "Georgian Architecture", explanation: "Gaya arsitektur Inggris abad ke-18 yang elegan dan simetris, berdasarkan proporsi klasik." },
          { term: "Neoclassical Architecture", explanation: "Gaya arsitektur akhir abad ke-18 yang kembali ke prinsip-prinsip klasik Yunani dan Romawi secara lebih ketat dan monumental." },
          { term: "Gothic Revival Architecture", explanation: "Gerakan kebangkitan kembali gaya arsitektur Gotik pada abad ke-19, sering disebut Neo-Gothic." },
          { term: "Adam Style", explanation: "Gaya Neoklasik interior dari Skotlandia yang ditandai dengan detail yang halus, elegan, dan terinspirasi dari seni Romawi." },
          { term: "Pombaline Style (Portuguese)", explanation: "Gaya arsitektur fungsional dan pragmatis di Lisbon setelah gempa 1755, dengan fitur anti-seismik." },
          { term: "Federal-Style Architecture", explanation: "Gaya Neoklasik Amerika awal, mirip dengan gaya Adam dan Georgian di Inggris." },
          { term: "Italianate Style Architecture", explanation: "Gaya arsitektur abad ke-19 yang terinspirasi dari vila-vila Renaisans Italia, dengan atap landai dan menara." },
          { term: "Empire Style", explanation: "Gaya Neoklasik Prancis pada masa Napoleon, megah dan terinspirasi oleh Kekaisaran Romawi." },
          { term: "Egyptian Revival", explanation: "Gaya arsitektur yang menggunakan motif dan citra dari Mesir kuno." },
          { term: "Regency Architecture", explanation: "Gaya arsitektur Inggris awal abad ke-19 yang elegan, dengan fasad stuko putih dan balkon besi tempa." },
          { term: "American Empire Style", explanation: "Versi Amerika dari gaya Empire Prancis, lebih sederhana namun tetap monumental." },
          { term: "Moorish Revival Architecture", explanation: "Gaya arsitektur abad ke-19 yang meniru arsitektur Moorish, sering digunakan pada sinagoge dan teater." },
          { term: "Biedermeier Architecture", explanation: "Gaya arsitektur dan desain kelas menengah di Eropa Tengah (1815-1848), sederhana, nyaman, dan fungsional." },
          { term: "Tudorbethan Architecture", explanation: "Kebangkitan kembali gaya arsitektur Tudor Inggris, sering disebut Mock Tudor." },
          { term: "Russian Revival Architecture", explanation: "Kebangkitan kembali arsitektur tradisional Rusia pada abad ke-19." },
          { term: "Victorian Architecture", explanation: "Arsitektur pada masa Ratu Victoria di Inggris, sangat beragam, ornamental, dan eklektik." },
          { term: "Jacobean Revival", explanation: "Kebangkitan kembali gaya arsitektur Jacobean (awal abad ke-17) di Inggris." },
          { term: "Romanesque Revival", explanation: "Kebangkitan kembali gaya Romanesque pada abad ke-19, dengan lengkungan bulat dan dinding batu yang masif." },
          { term: "Queenslander Architecture", explanation: "Gaya arsitektur rumah di Queensland, Australia, ditandai dengan konstruksi kayu, atap seng, dan beranda lebar." },
          { term: "Néo-Grec", explanation: "Gaya Neoklasik abad ke-19 yang terinspirasi oleh arsitektur Yunani secara lebih detail dan arkeologis." },
          { term: "Swiss Chalet Style", explanation: "Gaya arsitektur yang meniru rumah pedesaan di Pegunungan Alpen, dengan atap miring lebar dan balkon kayu berukir." },
          { term: "Arts and Crafts Movement", explanation: "Gerakan yang menolak produksi massal dan menekankan keahlian tangan, material alami, dan kesederhanaan." },
          { term: "Beaux-Arts Architecture", explanation: "Gaya arsitektur akademis dari Paris, monumental, simetris, dan sangat ornamental dengan detail klasik." },
          { term: "Second Empire Architecture", explanation: "Gaya yang berasal dari Prancis pada masa Napoleon III, ditandai dengan atap mansard yang khas." },
          { term: "Queen Anne Style", explanation: "Gaya arsitektur Victorian akhir yang asimetris, dengan menara, beranda melingkar, dan tekstur dinding yang beragam." },
          { term: "Parkitecture", explanation: "Gaya arsitektur Rustik yang dikembangkan oleh Dinas Taman Nasional AS, menggunakan kayu gelondongan dan batu lokal." },
          { term: "Shingle Style Architecture", explanation: "Gaya arsitektur Amerika yang menggunakan sirap kayu untuk menutupi atap dan dinding, menciptakan kesan volume yang menyatu." },
          { term: "Richardsonian Romanesque", explanation: "Gaya Romanesque Revival Amerika yang dipopulerkan oleh H.H. Richardson, dengan lengkungan bulat dan dinding batu yang kasar dan masif." },
          { term: "Chicago School Architecture", explanation: "Gaya arsitektur komersial di Chicago akhir abad ke-19, pelopor penggunaan rangka baja pada gedung tinggi." },
          { term: "American Renaissance", explanation: "Gerakan arsitektur dan seni di Amerika (1876-1917) yang menekankan afiliasi dengan seni klasik dan Renaisans Italia." },
          { term: "Modernisme", explanation: "Gerakan arsitektur dan seni di Spanyol (Catalan Modernisme) yang setara dengan Art Nouveau." },
          { term: "Art Nouveau Architecture", explanation: "Gaya akhir abad ke-19 yang terinspirasi dari alam, menggunakan garis-garis organik, melengkung, dan asimetris." },
          { term: "American Foursquare", explanation: "Gaya rumah Amerika yang berbentuk kotak (kubus), sederhana, dan praktis, biasanya dua lantai." },
          { term: "City Beautiful Movement", explanation: "Gerakan perencanaan kota di Amerika Utara (1890-an-1900-an) yang mempromosikan keindahan dan kemegahan monumental." },
          { term: "Colonial Revival Architecture", explanation: "Kebangkitan kembali gaya arsitektur kolonial Amerika pada akhir abad ke-19 dan awal abad ke-20." },
          { term: "Mission Revival Style", explanation: "Gaya arsitektur yang terinspirasi oleh misi-misi Spanyol di California, dengan dinding stuko dan atap genteng tanah liat." },
          { term: "Pueblo Architecture", explanation: "Arsitektur tradisional suku Pueblo di Amerika Barat Daya, menggunakan bata lumpur (adobe) dengan sudut membulat." },
          { term: "Garden City Movement", explanation: "Gerakan perencanaan kota yang memadukan perumahan, pertanian, dan industri dalam kota taman yang terencana." },
          { term: "Prairie School", explanation: "Gaya arsitektur Amerika yang dipelopori oleh Frank Lloyd Wright, menekankan garis horizontal, atap landai, dan integrasi dengan lanskap." },
          { term: "Edwardian Architecture", explanation: "Gaya arsitektur di Inggris pada masa Raja Edward VII, kurang ornamental dibanding Victoria, lebih dipengaruhi oleh Arts and Crafts dan Neoklasik." },
          { term: "National Romantic Style", explanation: "Gaya arsitektur di negara-negara Nordik awal abad ke-20 yang mencari inspirasi dari tradisi dan mitologi nasional." },
          { term: "Heliopolis Style", explanation: "Gaya arsitektur unik di distrik Heliopolis, Kairo, yang memadukan elemen Moorish, Persia, dan Eropa." },
          { term: "Futurist Architecture", explanation: "Gerakan arsitektur awal abad ke-20 yang merayakan kecepatan, teknologi, dan mesin." },
          { term: "Nordic Classicism", explanation: "Gaya arsitektur di negara-negara Nordik (1910-1930) yang memadukan elemen klasik dengan tradisi vernakular." },
          { term: "Expressionist Architecture", explanation: "Arsitektur awal abad ke-20 yang mengutamakan ekspresi emosional, seringkali dengan bentuk distorsi, fragmentasi, atau aneh." },
          { term: "Amsterdam School", explanation: "Variasi arsitektur Ekspresionis di Belanda, ditandai dengan penggunaan bata yang rumit dan bentuk organik." },
          { term: "Modern Architecture", explanation: "Gerakan arsitektur abad ke-20 yang menolak ornamen dan merangkul fungsionalisme, material industri, dan bentuk geometris sederhana." },
          { term: "Spanish Colonial Revival", explanation: "Gaya arsitektur awal abad ke-20 di AS yang terinspirasi oleh arsitektur kolonial Spanyol di Amerika." },
          { term: "Constructivist Architecture", explanation: "Gaya arsitektur avant-garde Soviet tahun 1920-an, menggabungkan teknologi canggih dengan tujuan sosial komunis." },
          { term: "Bauhaus Style", explanation: "Gaya arsitektur dari sekolah Bauhaus di Jerman, menekankan fungsionalisme, kesederhanaan, dan penggabungan seni dengan teknologi." },
          { term: "Mediterranean Revival", explanation: "Gaya arsitektur di AS tahun 1920-an-30-an yang meniru estetika vila di Spanyol, Italia, dan pesisir Mediterania." },
          { term: "Fascist Architecture", explanation: "Gaya arsitektur monumental dan simetris yang dipromosikan oleh rezim fasis di Italia dan Jerman." },
          { term: "Art Deco", explanation: "Gaya arsitektur dan desain tahun 1920-an-30-an yang glamor, dengan bentuk geometris, garis-garis tegas, dan ornamen mewah." },
          { term: "International Style (Internationalism)", explanation: "Gaya arsitektur Modernis utama (1920-an-30-an) yang menekankan volume daripada massa, keteraturan, dan penolakan ornamen." },
          { term: "Streamline Moderne", explanation: "Gaya Art Deco akhir yang terinspirasi dari aerodinamika, dengan sudut membulat, garis horizontal, dan permukaan halus." },
          { term: "Stalinist Architecture", explanation: "Arsitektur resmi Uni Soviet pada masa Stalin, monumental, klasik, dan seringkali sangat megah." },
          { term: "Nazi Architecture", explanation: "Arsitektur resmi Jerman Nazi, Neoklasik yang sangat besar dan intimidatif, dirancang untuk keabadian." },
          { term: "Usonian Architecture", explanation: "Konsep rumah kelas menengah Amerika oleh Frank Lloyd Wright, sederhana, satu lantai, dan terintegrasi dengan alam." },
          { term: "Mid-Century Modern", explanation: "Gaya arsitektur dan desain pertengahan abad ke-20 (1945-1965), ditandai dengan kesederhanaan, bentuk organik, dan koneksi ke alam." },
          { term: "Googie Architecture", explanation: "Gaya arsitektur futuristik yang dipengaruhi oleh budaya mobil dan Zaman Antariksa, dengan bentuk atap yang dramatis dan penggunaan neon." },
          { term: "Brutalist Architecture", explanation: "Gaya arsitektur yang menonjolkan beton mentah (béton brut), dengan bentuk-bentuk geometris yang masif dan balok-balok." },
          { term: "Critical Regionalism", explanation: "Pendekatan arsitektur yang melawan universalisme Modernisme dengan memasukkan konteks lokal (budaya, iklim) ke dalam desain." },
          { term: "Metabolism", explanation: "Gerakan arsitektur pasca-perang di Jepang yang membayangkan kota sebagai organisme hidup yang dapat tumbuh dan berubah, dengan struktur mega." },
          { term: "Postmodern Architecture", explanation: "Reaksi terhadap Modernisme pada akhir abad ke-20, membawa kembali ornamen, warna, dan referensi historis dalam bentuk yang seringkali ironis." },
          { term: "Shed Style", explanation: "Gaya arsitektur perumahan di AS (1960-an-70-an) yang ditandai dengan atap miring multi-level yang kompleks, memberikan tampilan seperti gudang (shed)." },
          { term: "High-Tech Architecture", explanation: "Gaya arsitektur yang mengekspos elemen teknis dan struktural bangunan, seperti pipa, saluran udara, dan rangka baja." },
          { term: "Arcology", explanation: "Konsep kota mandiri yang sangat padat dan terintegrasi dalam satu struktur raksasa untuk meminimalkan dampak lingkungan." },
          { term: "Memphis Group", explanation: "Gerakan desain Italia tahun 1980-an yang menentang aturan 'selera baik' dengan warna-warna cerah, bentuk asimetris, dan pola-pola liar." },
          { term: "Neo-Futurism", explanation: "Gerakan akhir abad ke-20 dan awal abad ke-21 yang membayangkan masa depan dengan teknologi canggih, bentuk organik, dan keberlanjutan." },
          { term: "Deconstructivism", explanation: "Gaya arsitektur akhir 1980-an yang ditandai dengan fragmentasi, ketidakstabilan visual, dan bentuk non-linear, menciptakan dislokasi yang terkendali." },
          { term: "Parametricism", explanation: "Gaya arsitektur avant-garde saat ini yang menggunakan algoritma komputer untuk menghasilkan bentuk-bentuk yang kompleks, fluida, dan saling terkait." },
          { term: "Contemporary Architecture", explanation: "Arsitektur saat ini (abad ke-21), sangat beragam dan tidak terikat pada satu gaya, seringkali menekankan keberlanjutan dan teknologi." },
          { term: "Blobitecture", explanation: "Arsitektur yang menggunakan bentuk-bentuk organik, amuba, dan membulat (blob)." },
          { term: "Neomodern", explanation: "Gaya yang melanjutkan prinsip-prinsip Modernisme tetapi dengan kompleksitas dan materialitas yang lebih baru." },
          { term: "Sustainable Architecture", explanation: "Arsitektur yang dirancang untuk meminimalkan dampak lingkungan, sering disebut arsitektur hijau." },
          { term: "New Classical Architecture", explanation: "Gerakan kontemporer yang melanjutkan praktik arsitektur klasik tradisional." }
        ]
      }
    ]
  },
  {
    collectionTitle: "Interior Design Styles",
    categories: [
      {
        title: "Styles",
        keywords: [
          { term: "Stone Age", explanation: "Desain interior paling awal yang menggunakan gua sebagai tempat berlindung dengan lukisan dinding sederhana." },
          { term: "Neolithic Europe", explanation: "Interior prasejarah yang mulai menggunakan mebel sederhana dari batu dan struktur kayu." },
          { term: "Ancient Egyptian", explanation: "Interior Mesir kuno yang kaya akan hieroglif, mural, dan perabotan berukir yang megah untuk firaun." },
          { term: "Roman Empire", explanation: "Interior Romawi kuno yang menampilkan mozaik, fresko, dan perabotan yang terinspirasi dari Yunani dengan penekanan pada kemewahan." },
          { term: "The Dark Ages", explanation: "Periode Awal Abad Pertengahan dengan interior sederhana, fungsional, menggunakan kayu kasar dan sedikit ornamen." },
          { term: "The Byzantine Empire", explanation: "Interior Bizantium yang mewah dengan penggunaan mozaik emas, kubah, dan ikonografi Kristen yang kaya." },
          { term: "The Renaissance Period", explanation: "Interior Renaisans yang terinspirasi oleh seni klasik, menekankan simetri, proporsi, dan keindahan artistik." },
          { term: "Gothic", explanation: "Interior Gotik yang ditandai dengan lengkungan runcing, jendela kaca patri, dan ukiran kayu yang rumit." },
          { term: "Baroque", explanation: "Gaya interior abad ke-17 yang dramatis, mewah, dan penuh ornamen, dengan penekanan pada kemegahan." },
          { term: "Traditional", explanation: "Gaya interior yang mengacu pada desain klasik Eropa abad ke-18 dan ke-19, elegan dan formal." },
          { term: "Rococo", explanation: "Gaya interior pertengahan abad ke-18 yang lebih ringan dan feminin dari Baroque, dengan kurva, motif kerang, dan warna pastel." },
          { term: "The Industrial Revolution", explanation: "Interior yang dipengaruhi oleh era industri, mengekspos material seperti besi cor, bata, dan elemen fungsional." },
          { term: "Neoclassical Style", explanation: "Gaya interior akhir abad ke-18 yang kembali ke keanggunan dan kesederhanaan arsitektur Yunani dan Romawi." },
          { term: "Tropical", explanation: "Gaya interior yang terinspirasi dari daerah tropis, menggunakan material alami, tanaman, dan warna-warna cerah." },
          { term: "Aesthetic Movement", explanation: "Gerakan akhir abad ke-19 yang mengutamakan keindahan ('Art for Art's Sake'), dengan pengaruh dari seni Jepang." },
          { term: "Tuscan", explanation: "Gaya interior yang terinspirasi dari pedesaan Tuscany, Italia, dengan warna hangat, material alami, dan nuansa rustik." },
          { term: "Arts & Crafts", explanation: "Gaya interior yang menekankan keahlian tangan, material alami seperti kayu ek, dan kesederhanaan bentuk." },
          { term: "Rustic Style", explanation: "Gaya interior yang menonjolkan keindahan material alami yang kasar dan tidak diolah, seperti kayu gelondongan dan batu." },
          { term: "Modernism", explanation: "Gerakan awal abad ke-20 yang menolak ornamen dan fokus pada kesederhanaan, garis bersih, dan fungsionalitas." },
          { term: "Art Nouveau", explanation: "Gaya interior akhir abad ke-19 yang menggunakan garis-garis organik melengkung yang terinspirasi dari alam." },
          { term: "Colonial Revival", explanation: "Kebangkitan kembali gaya interior dari masa kolonial Amerika, menampilkan simetri dan detail klasik." },
          { term: "Eclectic Style", explanation: "Gaya interior yang memadukan elemen dari berbagai periode dan gaya yang berbeda secara harmonis." },
          { term: "Modern", explanation: "Gaya desain yang berakar dari Modernisme, menekankan garis bersih, palet warna sederhana, dan ketiadaan ornamen." },
          { term: "Bauhaus", explanation: "Gaya interior yang lahir dari sekolah Bauhaus Jerman, mengutamakan fungsionalitas dan penggabungan seni dengan industri." },
          { term: "Country", explanation: "Gaya interior yang terinspirasi dari rumah pedesaan, nyaman, dan sederhana, dengan perabotan kayu dan tekstil tradisional." },
          { term: "Art Deco", explanation: "Gaya interior tahun 1920-an-30-an yang glamor, dengan bentuk geometris, material mewah, dan pola simetris." },
          { term: "Mediterranean", explanation: "Gaya interior yang terinspirasi dari negara-negara Mediterania, dengan dinding plester, warna laut dan tanah, serta material alami." },
          { term: "Surrealism", explanation: "Gaya interior yang dipengaruhi oleh seni Surealisme, menciptakan ruang yang aneh, tak terduga, dan seperti mimpi." },
          { term: "Mid-Century Modern", explanation: "Gaya interior dari pertengahan abad ke-20, ditandai dengan fungsionalitas, garis bersih, bentuk organik, dan koneksi ke alam." },
          { term: "Scandinavian Modern", explanation: "Gaya interior dari negara-negara Nordik yang menekankan kesederhanaan, fungsionalitas, cahaya alami, dan penggunaan kayu terang." },
          { term: "Transitional", explanation: "Gaya interior yang merupakan jembatan antara gaya Tradisional dan Modern, menciptakan keseimbangan yang elegan dan nyaman." },
          { term: "Postmodernism", explanation: "Gaya interior tahun 1980-an yang menolak aturan Modernisme, menggunakan warna cerah, bentuk tak terduga, dan humor." },
          { term: "Contemporary", explanation: "Gaya interior masa kini, yang terus berkembang, ditandai dengan garis bersih, ruang terbuka, dan palet warna netral." },
          { term: "Minimalism", explanation: "Gaya interior yang mengurangi segalanya ke elemen esensial, menggunakan ruang negatif dan palet warna monokromatik." },
          { term: "Vintage", explanation: "Gaya interior yang menggunakan perabotan dan dekorasi dari era sebelumnya, terutama dari tahun 1940-an hingga 1960-an." },
          { term: "French Provincial", explanation: "Gaya interior pedesaan Prancis yang elegan namun nyaman, dengan perabotan berukir dan kain bermotif." },
          { term: "Japanese Interior Design", explanation: "Desain interior Jepang yang menekankan minimalisme, alam, dan ketenangan, sering menggunakan kayu, kertas, dan elemen Zen." },
          { term: "Moroccan Interior Design", explanation: "Gaya interior Maroko yang kaya warna, dengan tekstil berlapis, lentera logam, dan ubin berpola geometris." },
          { term: "Indian Interior Design", explanation: "Desain interior India yang semarak, menggunakan warna-warna cerah, ukiran kayu yang rumit, dan tekstil sutra." },
          { term: "Bohemian (Boho) Style", explanation: "Gaya interior yang bebas, eklektik, dan tidak konvensional, dengan banyak lapisan tekstil, tanaman, dan barang-barang dari perjalanan." },
          { term: "Industrial Interior Design", explanation: "Gaya interior yang terinspirasi dari pabrik atau gudang, mengekspos bata, pipa, dan beton dengan perabotan fungsional." },
          { term: "African Interior Design", explanation: "Desain interior yang terinspirasi dari Afrika, menggunakan warna-warna bumi, material alami, dan pola-pola suku yang berani." },
          { term: "Chinese Interior Design", explanation: "Desain interior Tiongkok yang menekankan keseimbangan (Feng Shui), dengan penggunaan kayu gelap bervernis dan detail ornamen." },
          { term: "Victorian Interior Design", explanation: "Gaya interior era Victoria yang maksimalis, dengan ornamen yang rumit, warna-warna gelap, dan perabotan yang berat." },
          { term: "Southwestern Interior Design", explanation: "Gaya interior yang terinspirasi dari gurun Amerika Barat Daya, dengan warna terakota, tekstur kasar, dan pengaruh budaya asli Amerika." },
          { term: "Nordic Minimalism", explanation: "Versi yang lebih minimalis dari gaya Skandinavia, sangat fokus pada fungsionalitas, garis yang sangat bersih, dan palet warna yang diredam." }
        ]
      }
    ]
  }
];
